import Form from "next/form";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
  
export default function RootLayout({ children }) {
    return (
      <html lang="en">
          <body>
            <Form action="/movies">            
                    <label htmlFor="idTitleSearchKey">Título:</label>
                    <input id="idTitleSearchKey" name="titleSearchKey" />
        
                    <label htmlFor="idTypeSearchKey">Tipo:</label>
                    <select id="idTypeSearchKey" name="typeSearchKey">
                    <option value="movie">Filme</option>
                    <option value="series">Série</option>
                    </select>
        
                    <button type="submit">Pesquisar</button>
                </Form>
            {children}
          </body>
      </html>
    )
}
  