export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout")
  return (
    <html lang="en">
        <body>
          <header>
            <div>
              <p>Menu principal</p>
              <h1>
                    Viva Santana!
              </h1>
            </div>
          </header>
          {children}
        </body>
    </html>
  )
}
