export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
            <div>
                <header>
                    <h1>Nova Rota 2</h1>
                </header>
                {children}
            </div>
        </body>
      </html>
    );
  }